# Generated by Django 4.2 on 2023-10-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa_organu_egzekucyjnego",
                    models.CharField(
                        max_length=255, verbose_name="Nazwa organu egzakucyjnego"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "nr_sprawy",
                    models.CharField(max_length=255, verbose_name="Numer sprawy"),
                ),
                (
                    "owner_data",
                    models.CharField(max_length=255, verbose_name="Dane właściciela"),
                ),
            ],
            options={"verbose_name": "Raport", "verbose_name_plural": "Raport",},
        ),
    ]
