# Generated by Django 4.2 on 2023-10-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_manager", "0002_report"),
    ]

    operations = [
        migrations.RemoveField(model_name="report", name="created_at",),
        migrations.AddField(
            model_name="report",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
